[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./broadcast" },
    { access = "read", path = "./" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc_version = '0.8.26'
evm_version = "cancun"  # hard fork that enabled EIP-1153
optimizer_runs = 800
via_ir = false
ffi = true
bytecode_hash = "none"

etherscan_api_key = "${ETHERSCAN_API_KEY}"
[etherscan]
unichain = { key = "${ETHERSCAN_API_KEY}" }

[lint]
exclude_lints = ["unaliased-plain-import", "screaming-snake-case-immutable", "mixed-case-variable", "mixed-case-function", "divide-before-multiply", "named-struct-fields", "unsafe-typecast", "unwrapped-modifier-logic", "unsafe-cheatcode"]
ignore = [
    "./test/libraries/math/**/*.sol",
    "./test/libraries/v4-forks/**/*.sol",
    "./test/libraries/TestAccountLib.t.sol",
    "./external/**/*.sol"
]